spring:
  application:
    name: "crypto"
server:
  port: 8080

profileDetails:
  crypto:
    message: "Welcome to Crypto Conversion related Development profile"
    contactDetails:
      name: "Shiv Patel"
      role: "DEV"
      email: "{cypher}4ca8cdbf437994fbe83971d95fbda35071ccfa8cd1a1f0e816ccac70ad583ec61e8c903449703da1cedd794ac12f83c4"