spring:
  application:
    name: "crypto"
server:
  port: 8081

profileDetails:
  crypto:
    message: "Welcome to Crypto Conversion related main profile"
    contactDetails:
      name: "Gaurav Verma"
      role: "ADMIN"
      email: "{cipher}3149daed4851a2893f216443fb6787543a136a0ef4845b4f6317a22fa6e4854a5655bda150c785a09f36a791067c6d71"
